### ISSUE TITLE
default the atis-bridge-sdk to ON

### ISSUE THREAD

**Issue by arrenglover** [event-driven-robotics/atis-gen3-docker#1]
it might be useful to default the event-driven library to compile and install the atis-bridge-sdk.
`-DBUILD_APPLICATIONS=ON -Denable_ATIS3=ON` <- double check i haven't made a typo here.

okay but to build it correctly there is a library missing.

`apt update` <- for me it doesn't work without this update
`apt install libboost-chrono-dev`

**Comment by Iaxama** [comment]
Fixed by fbfdfb4d1342d1bca75b79e10e202c84e779910e

**Comment by Iaxama** [comment]
@arrenglover
