### ISSUE TITLE
Cannot visualize the output from the vFramer as per the instructions

### ISSUE THREAD

**Issue by xEnVrE** [event-driven-robotics/atis-gen3-docker#2]
I am trying to follow the instructions in https://github.com/event-driven-robotics/atis-gen3-docker#use-the-container, in order to verify that the yarp side of the appliance is working as expected.

What I did:
1. Created a new container using the `eventdrivenrobotics/atis-gen3:latest`
2. Run the `yarpserver`
3. Run the bridge `atis-bridge-sdk`

At this point, I would like to test the output of the `vFramer` to be sure that everything is working properly. I though I could use the `atis3-vis` application within the `yarpmanager`, however that application is not available within the container. Am I doing something wrong?

Nonetheless, I tried opening the `vFramer`. However, it seems that there is no such executable. Instead, I found one called `vFramerLite`, accepting events in two input ports `/vFramer/Left/AE:i` and `/vFramer/Right/AE:i`. I then tried to connect `/atis3/AE:o` to `/vFramer/Left/AE:i` (not sure if this makes any sense, though). The module is unfortunately crashing (specifically I get a `Segmentation fault (core dumped))`.

How should I proceed? Is there an example of any configuration `ini` file I should pass to the `vFramerLite` application in order to make it work for my configuration considering a single event camera?

Thank you

cc @arrenglover @Iaxama @LZC-68

**Comment by arrenglover** [comment]
Hi @xEnVrE , thanks for the feedback:

try using `vFramerLite --height 480 --width 640`

Otherwise, to try to fix it, I would try to pull master and rebuild the event-driven library as it is probably too old:
`cd /usr/local/src/event-driven/build`
`git pull`
`cmake ..`
`make install`

1. `atis3-vis`  - maybe this doesn't exist sorry.
2. yes `vFramerLite` is the correct application and not `vFramer` (for now)

It would be better for us to start to use a new version of `event-driven` which works better using the new generation cameras. Not everything is stable but it is the better option. try checking out `ev2-dev` branch of `event-driven` and see if it compiles. I can help you on Thursday if you need.

**Comment by xEnVrE** [comment]
Dear @arrenglover, 

thanks for your response. I will proceed then by checking out `ev2-dev` and recompiling it.

Any change I can contribute by creating, e.g., a branch in this repository with the updated `docker` recipe (and maybe an alternative "unstable" image which already checks out and compile the `ev2-dev` branch)?

Thanks, I'll keep you posted.

**Comment by arrenglover** [comment]
yes let's move to `ev2-dev`, but there will be more undocumented changes on how to do things, I can support you easily though.

Yes please if we can update any of the instructions / docker images to be up to date from your experience would be great. Thanks.

**Comment by xEnVrE** [comment]
For these days we will be using two forks with specific branches, e.g. 
- https://github.com/xEnVrE/event-driven-docker/tree/v/bionic_3.3.2_ev2
- https://github.com/xEnVrE/atis-gen3-docker/tree/v/bionic_3.3.2_ev2

each containing a temporary `build_image` script in the root. Running the two scripts will generate one intermediate docker image

```
eventdrivenrobotics/event-driven:bionic_yarp_v3.3.2_ed_ev2-dev
```

that is used to build the final image

```
eventdrivenrobotics/atis-gen3:ev2-dev
```

I'll let you know if we are able to run the `vFramerLite` using the `ev2-dev` branch. We can talk f2f on how to incorporate changes upstream.

**Comment by arrenglover** [comment]
FYI in ev2-dev you'll need to run it as `vFramer --height 480 --width 640 --iso`and it should display automatically after connecting the port i.e. `yarp connect /atis3/AE:o /vFramer/iso/AE:i fast_tcp`

**Comment by xEnVrE** [comment]
I tried to connect the `/atis3/AE:o` port, opened by the `atis-bridge-sdk`, to the `/vFramer/iso/AE:i` port.

After the connection we get:
- on the `atis-bridge-sdk`:
  (before connecting the ports)
  ```
  (...)
  [INFO]948 packets and 605.734 k events sent per second 
  [INFO]899 packets and 88.829 k events sent per second 
  [INFO]907 packets and 115.244 k events sent per second 
  [INFO]901 packets and 81.596 k events sent per second 
  [INFO]901 packets and 54.453 k events sent per second 
  [INFO]959 packets and 1035.07 k events sent per second 
  [INFO]1008 packets and 1404.38 k events sent per second 
  [INFO]1000 packets and 1700.81 k events sent per second 
  [INFO]934 packets and 557.735 k events sent per second 
  [INFO]948 packets and 688.471 k events sent per second 
  [INFO]909 packets and 38.25 k events sent per second 
  [INFO]913 packets and 30.493 k events sent per second
  ```
  (after connecting the ports)
  ``` 
  yarp: Sending output from /atis3/AE:o to /vFramer/iso/AE:i using tcp
  [INFO]Buffer 0 resized to 4000000 
  [INFO]90 packets and 4.778 k events sent per second 
  [INFO]0 packets and 0 k events sent per second 
  [INFO]0 packets and 0 k events sent per second 
  [INFO]0 packets and 0 k events sent per second
   ```
  i.e., it seems it stopped sending packets?
- on the `vFramer`:
   (after connecting the ports)
  ```
   yarp: Receiving input from /atis3/AE:o to /vFramer/iso/AE:i using tcp
   [ERROR]Invalid Packet: not 3 elements 
   [WARNING]port read failure!
   ```

Are we doing something wrong? 

Thank you

**Comment by arrenglover** [comment]
seems like the atis-bridge isn't on ev2-dev so make sure that in event-driven is on branch ev2-dev and then it should compile the atis-bridge. `make install` should overwrite the old atis-bridge (from the master branch)

**Comment by xEnVrE** [comment]
I found the problem. Although the image on which the `eventdrivenrobotics/atis-gen3` docker is based on takes into account the branch name of `event-driven`, the final Dockerfile of `eventdrivenrobotics/atis-gen3` is focing the `master` branch:

https://github.com/event-driven-robotics/atis-gen3-docker/blob/e0298bd1524f70dba74b3626ad99de2b30f33ae3/Dockerfile#L45

I have just fixed it.

The same docker file is setting three build flags, namely:

https://github.com/event-driven-robotics/atis-gen3-docker/blob/e0298bd1524f70dba74b3626ad99de2b30f33ae3/Dockerfile#L46-L48

The first two seem not to be available anymore in the `ev2-dev` branch. However, the last one is available. Should I still set it, i.e. `VLIB_CLOCK_PERIOD_NS=1000` instead of the default `=80` ?

**Comment by xEnVrE** [comment]
Seems to be working as expected now:

![image](https://user-images.githubusercontent.com/6014499/170443919-6c01cb48-04cd-4f42-8682-740efa8d934e.png)

I'll wait for your answer about the `VLIB_CLOCK_PERIOD_NS` before closing the issue.

**Comment by arrenglover** [comment]
looks good! yes please leave `VLIB_CLOCK_PERIOD_NS=1000`

**Comment by arrenglover** [comment]
to perform the calibration you should set the `vFramer --black --yarp_publish --height 480 --width 640`to achieve the result that is in the calibration readme

**Comment by xEnVrE** [comment]
I think we can close this and continue the discussion on the calibration in https://github.com/robotology/event-driven/issues/162

Thanks for the support
